version: "3"

services:
  bot:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-bot
    restart: unless-stopped

  tests:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    command: "yarn test"
    env_file: .env
    environment:
      - MAINNET_RPC_URL=http://hardhat:8545
    container_name: zodiac-tests
    depends_on:
      - hardhat
    networks:
      - zodiac-bots-network

  hardhat:
    build:
      context: .
      dockerfile: ./Dockerfile.hardhat-container
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-hardhat-fork
    restart: unless-stopped
    networks:
      - zodiac-bots-network

networks:
  zodiac-bots-network:
