version: "3"

services:
  # Executes the bot only, without extra services
  bot:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-bot
    restart: unless-stopped

  # Starts services (DB, HardHat) and the bot
  bot-dev:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-bot-dev
    restart: unless-stopped
    depends_on:
      - db
      - hardhat
      - smtp
    networks:
      - zodiac-bots-network

  # Starts services and runs the test suite
  tests:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    command: "yarn test"
    env_file: .env
    environment:
      - MAINNET_RPC_URL=http://hardhat:8545
    container_name: zodiac-tests
    depends_on:
      - hardhat
      - db
      - smtp
    networks:
      - zodiac-bots-network

  # Hardhat Instance, controllable via RPC
  hardhat:
    build:
      context: .
      dockerfile: ./Dockerfile.hardhat-container
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-hardhat-fork
    restart: unless-stopped
    networks:
      - zodiac-bots-network

  # PostgreSQL instance for persistance
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=zodiac-bots
      - POSTGRES_USER=zodiac-bots
      - POSTGRES_DB=zodiac-bots
    container_name: zodiac-db
    networks:
      - zodiac-bots-network

  smtp:
    image: maildev/maildev
    environment:
      - MAILDEV_WEBMAIL_USER=kleros
      - MAILDEV_WEBMAIL_PASSWORD=sorelk
    container_name: zodiac-smtp
    networks:
      - zodiac-bots-network

networks:
  zodiac-bots-network:
