FROM node:20.12.1-alpine

ARG ETHERSCAN_API_KEY
ENV ETHERSCAN_API_KEY $ETHERSCAN_API_KEY

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package.json hardhat.config.ts tsconfig.json ./

RUN yarn install && yarn cache clean

CMD ["node_modules/.bin/hardhat", "node", "--verbose"]