version: "3"

services:
  zodiac-bot:
    build:
      context: .
      args:
        - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    env_file: .env
    container_name: zodiac-bot
    restart: unless-stopped
